# apiVersion: security.istio.io/v1beta1
# kind: RequestAuthentication
# metadata:
#   name: book-ra
#   labels:
#     app: vadal-echo-ra
# spec:
#   selector:
#     matchLabels:
#       app: vadal-echo
#   jwtRules:
#     - forwardOriginalToken: true
#       outputPayloadToHeader: x-jwt-payload
#       issuer: "http://localhost:8080/realms/Istio-Keycloak"
#       jwksUri: "http://localhost:8080/realms/Istio-Keycloak/protocol/openid-connect/certs"

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: require-jwt
  namespace: demo
spec:
  selector:
    matchLabels:
      app: books
  action: ALLOW
  rules:
  - from:
    - source:
       requestPrincipals: ["*"]
    when:
    - key: request.auth.claims[realm_access][roles]
      values: ["user"]

---
# apiVersion: security.istio.io/v1beta1
# kind: AuthorizationPolicy
# metadata:
#   name: books-request-authentication
#   namespace: demo
# spec:
#   selector:
#     matchLabels:
#        app: books
#   rules:
#    - from:
#      - source:
#          requestPrincipals: ["*"]

